/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzwtec_watchdog_jni_WatchDogImp */

#ifndef _Included_com_zzwtec_watchdog_jni_WatchDogImp
#define _Included_com_zzwtec_watchdog_jni_WatchDogImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzwtec_watchdog_jni_WatchDogImp
 * Method:    FeedDog
 * Signature: (Lcom/zzwtec/watchdog/model/DogFood;)I
 */
JNIEXPORT jint JNICALL Java_com_zzwtec_watchdog_jni_WatchDogImp_FeedDog
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
