/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzwtec_camera_fx_service_watchdog_WatchDogService */

#ifndef _Included_com_zzwtec_camera_fx_service_watchdog_WatchDogService
#define _Included_com_zzwtec_camera_fx_service_watchdog_WatchDogService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzwtec_camera_fx_service_watchdog_WatchDogService
 * Method:    FeedDog
 * Signature: (Lcom/zzwtec/camera/fx/model/DogFood;)I
 */
JNIEXPORT jint JNICALL Java_com_zzwtec_camera_fx_service_watchdog_WatchDogService_FeedDog
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
